In [1]:
import math as m
import numpy as np

In [2]:
def normalize(vec):
    nvec = np.array(vec)
    return nvec / np.linalg.norm(nvec)

In [3]:
def rotator(angles):
    a, b, g = angles
    gr = np.array([[m.cos(g), m.sin(g), 0.], [-m.sin(g), m.cos(g), 0.], [0., 0., 1.]])
    br = np.array([[m.cos(b), 0., -m.sin(b)], [0., 1., 0.], [m.sin(b), 0., m.cos(b)]])
    ar = np.array([[m.cos(a), m.sin(a), 0.], [-m.sin(a), m.cos(a), 0.], [0., 0., 1.]])     
    return gr @ br @ ar

In [4]:
3. / m.sqrt(10.), 1. / m.sqrt(10.) 

(0.9486832980505138, 0.31622776601683794)

In [5]:
rotator((m.pi / 2., m.atan(1. / 3.), -m.pi / 2.))

array([[ 1.00000000e+00, -3.14224174e-18, -1.93633661e-17],
       [-3.14224174e-18,  9.48683298e-01, -3.16227766e-01],
       [ 1.93633661e-17,  3.16227766e-01,  9.48683298e-01]])

In [6]:
import scipy.optimize as opt

In [7]:
def rotate(xs, ags):
    return rotator(ags) @ xs

In [8]:
normalize([0., 1., 3.])

array([0.        , 0.31622777, 0.9486833 ])

In [9]:
res = normalize([0., 1., 3.])
ort = np.array([0., 0., 1.])
fopt = lambda x: rotate(ort, x) - res

In [47]:
result = opt.root(fopt, np.random.rand(3))

In [48]:
result

    fjac: array([[-0.78925542,  0.56599867, -0.2381625 ],
       [ 0.44681294,  0.79538416,  0.40953906],
       [ 0.42122924,  0.21681684, -0.88065679]])
     fun: array([-1.34343852e-13,  7.08322290e-14, -2.35367281e-14])
 message: 'The solution converged.'
    nfev: 25
     qtf: array([-1.31808663e-10,  1.14754882e-11,  1.76476640e-11])
       r: array([ 0.16005979,  0.98957654, -0.03084766,  0.31028766,  0.08577842,
        0.04781004])
  status: 1
 success: True
       x: array([1.56462908, 0.32175055, 1.57079633])

In [25]:
m.atan(1/3)

0.3217505543966422

In [26]:
result["x"][2] / m.pi

-0.5000000000000008

In [27]:
result["x"][0] / m.pi

102.04485933774792

In [28]:
rot = rotator(result["x"])

In [29]:
rot

array([[ 1.40463723e-01, -9.90085826e-01, -7.53019997e-16],
       [ 9.39277887e-01,  1.33255588e-01,  3.16227766e-01],
       [-3.13092629e-01, -4.44185294e-02,  9.48683298e-01]])

In [30]:
np.linalg.eig(rotator(result["x"]))

(array([0.1112013+0.9937979j, 0.1112013-0.9937979j, 1.       +0.j       ]),
 array([[ 0.0204663 +0.69506787j,  0.0204663 -0.69506787j,
         -0.18144851+0.j        ],
        [ 0.69827875+0.j        ,  0.69827875-0.j        ,
          0.15752329+0.j        ],
        [-0.10948938+0.12992556j, -0.10948938-0.12992556j,
          0.97070225+0.j        ]]))

In [36]:
rot @ ort - res

array([-7.53019997e-16, -2.77555756e-16,  1.11022302e-16])

In [32]:
rotator([m.pi / 2., m.atan(1. / 3.), -m.pi / 2.]) @ ort

array([-1.93633661e-17, -3.16227766e-01,  9.48683298e-01])

In [38]:
rotator([-m.pi / 2., m.atan(1. / 3.), m.pi / 2.]) @ ort - res

array([-1.93633661e-17,  0.00000000e+00,  0.00000000e+00])

In [33]:
rotator([m.pi / 2., m.atan(1. / 3.), -m.pi / 2.])

array([[ 1.00000000e+00, -3.14224174e-18, -1.93633661e-17],
       [-3.14224174e-18,  9.48683298e-01, -3.16227766e-01],
       [ 1.93633661e-17,  3.16227766e-01,  9.48683298e-01]])

In [41]:
np.random.rand(10)

array([0.3984213 , 0.71478173, 0.21025198, 0.46680496, 0.8304873 ,
       0.67965083, 0.11108842, 0.64174635, 0.10757734, 0.6175859 ])

In [42]:
def adopt(x):
    n = int(0.5 * x / m.pi)
    return x - 2. * m.pi * float(n)

In [46]:
adopt(6.4) - (6.4 - 2. * m.pi)

0.0